In [1]:
import pandas as pd
import numpy as np
import optimization as opt
import matplotlib.pyplot as plt
import geopandas as gpd
import pydeck as pdk
pdk.settings.rendering = "iframe"

import optimization_plots
import importlib

importlib.reload(optimization_plots)
importlib.reload(opt)

ERROR 1: PROJ: proj_create_from_database: Open of /home/konni/anaconda3/envs/velux_opt/share/proj failed

In [2]:
data_for_optimizer_pre = pd.read_csv('lpjguess_optimizer_data_unnormalized.csv', sep=';').set_index(['Lon', 'Lat', 'ES', 'ssp'])

In [3]:
importlib.reload(opt)
data_for_optimizer = data_for_optimizer_pre.groupby(['Lon', 'Lat'], group_keys=False).apply(lambda grp: opt.prepare_for_optimization(grp, ['Lon', 'Lat'], 'ssp'))

In [4]:
data_for_optimizer

                                 spbau_manbau  spbau_shortrot  spbau_longrot  \
Lon    Lat   ssp     management
-8.75  42.75 cpool   ssp126          1.000000        1.000000       1.000000
                     ssp585          1.000000        1.000000       1.000000
             harvest ssp126          0.000000        0.000000       0.000000
                     ssp585          0.000000        0.000000       0.000000
             litter  ssp126          0.062133        0.062133       0.062133
...                                       ...             ...            ...
 24.75 61.75 harvest ssp585          0.000000        0.000000       0.000000
             litter  ssp126          0.130635        0.132006       0.129465
                     ssp585          0.131809        0.132930       0.130463
             shannon ssp126          0.091363        0.088200       0.096127
                     ssp585          0.062131        0.057739       0.063560

                                 spbau_stop  tobd_manbau  tobd_shortrot  \
Lon    Lat   ssp     management
-8.75  42.75 cpool   ssp126        1.000000     1.000000       1.000000
                     ssp585        1.000000     1.000000       1.000000
             harvest ssp126        0.000000     0.000000       0.000000
                     ssp585        0.000000     0.000000       0.000000
             litter  ssp126        0.062133     0.062137       0.062137
...                                     ...          ...            ...
 24.75 61.75 harvest ssp585        0.000000     0.000000       0.000000
             litter  ssp126        0.106186     0.147491       0.149093
                     ssp585        0.113267     0.142242       0.140741
             shannon ssp126        0.108810     0.071497       0.065964
                     ssp585        0.093252     0.040476       0.036461

                                 tobd_longrot  tone_manbau  tone_shortrot  \
Lon    Lat   ssp     management
-8.75  42.75 cpool   ssp126          1.000000     1.000000       1.000000
                     ssp585          1.000000     1.000000       1.000000
             harvest ssp126          0.000000     0.000000       0.000000
                     ssp585          0.000000     0.000000       0.000000
             litter  ssp126          0.062137     0.087726       0.089658
...                                       ...          ...            ...
 24.75 61.75 harvest ssp585          0.000000     0.000000       0.000000
             litter  ssp126          0.152413     0.127221       0.129284
                     ssp585          0.140783     0.134004       0.133434
             shannon ssp126          0.072286     0.097020       0.091245
                     ssp585          0.046690     0.062151       0.057552

                                 tone_longrot
Lon    Lat   ssp     management
-8.75  42.75 cpool   ssp126          1.000000
                     ssp585          1.000000
             harvest ssp126          0.000000
                     ssp585          0.000000
             litter  ssp126          0.084782
...                                       ...
 24.75 61.75 harvest ssp585          0.000000
             litter  ssp126          0.125926
                     ssp585          0.128648
             shannon ssp126          0.098268
                     ssp585          0.067352

[2192 rows x 10 columns]

In [5]:
importlib.reload(opt)
weights = [1.0, 1.0, 1.0, 1.0]
optimized_data_original = data_for_optimizer.groupby(['Lon', 'Lat'], group_keys=False).apply(lambda gc: opt.optimize_gridcell(gc, gc.name, ['ssp126', 'ssp585'], es_weights=weights))

Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.
Warning: 2 rows where found where an indicator for an RCP had all zeros for each strategy.

In [6]:
optimized_data_original

              spbau_manbau  spbau_shortrot  spbau_longrot  spbau_stop  \
Lon    Lat
-8.75  42.75           1.0             0.0            0.0         0.0
       43.25           1.0             0.0            0.0         0.0
-8.25  42.25           1.0             0.0            0.0         0.0
       42.75           1.0             0.0            0.0         0.0
       43.25           1.0             0.0            0.0         0.0
...                    ...             ...            ...         ...
 23.75 62.25           1.0             0.0            0.0         0.0
 24.25 61.25           1.0             0.0            0.0         0.0
       61.75           1.0             0.0            0.0         0.0
       62.25           1.0             0.0            0.0         0.0
 24.75 61.75           1.0             0.0            0.0         0.0

              tobd_manbau  tobd_shortrot  tobd_longrot  tone_manbau  \
Lon    Lat
-8.75  42.75          0.0            0.0           0.0          0.0
       43.25          0.0            0.0           0.0          0.0
-8.25  42.25          0.0            0.0           0.0          0.0
       42.75          0.0            0.0           0.0          0.0
       43.25          0.0            0.0           0.0          0.0
...                   ...            ...           ...          ...
 23.75 62.25          0.0            0.0           0.0          0.0
 24.25 61.25          0.0            0.0           0.0          0.0
       61.75          0.0            0.0           0.0          0.0
       62.25          0.0            0.0           0.0          0.0
 24.75 61.75          0.0            0.0           0.0          0.0

              tone_shortrot  tone_longrot
Lon    Lat
-8.75  42.75            0.0           0.0
       43.25            0.0           0.0
-8.25  42.25            0.0           0.0
       42.75            0.0           0.0
       43.25            0.0           0.0
...                     ...           ...
 23.75 62.25            0.0           0.0
 24.25 61.25            0.0           0.0
       61.75            0.0           0.0
       62.25            0.0           0.0
 24.75 61.75            0.0           0.0

[274 rows x 10 columns]

In [8]:
optimized_data_original

              spbau_manbau  spbau_shortrot  spbau_longrot  spbau_stop  \
Lon    Lat
-8.75  42.75           1.0             0.0            0.0         0.0
       43.25           1.0             0.0            0.0         0.0
-8.25  42.25           1.0             0.0            0.0         0.0
       42.75           1.0             0.0            0.0         0.0
       43.25           1.0             0.0            0.0         0.0
...                    ...             ...            ...         ...
 23.75 62.25           1.0             0.0            0.0         0.0
 24.25 61.25           1.0             0.0            0.0         0.0
       61.75           1.0             0.0            0.0         0.0
       62.25           1.0             0.0            0.0         0.0
 24.75 61.75           1.0             0.0            0.0         0.0

              tobd_manbau  tobd_shortrot  tobd_longrot  tone_manbau  \
Lon    Lat
-8.75  42.75          0.0            0.0           0.0          0.0
       43.25          0.0            0.0           0.0          0.0
-8.25  42.25          0.0            0.0           0.0          0.0
       42.75          0.0            0.0           0.0          0.0
       43.25          0.0            0.0           0.0          0.0
...                   ...            ...           ...          ...
 23.75 62.25          0.0            0.0           0.0          0.0
 24.25 61.25          0.0            0.0           0.0          0.0
       61.75          0.0            0.0           0.0          0.0
       62.25          0.0            0.0           0.0          0.0
 24.75 61.75          0.0            0.0           0.0          0.0

              tone_shortrot  tone_longrot
Lon    Lat
-8.75  42.75            0.0           0.0
       43.25            0.0           0.0
-8.25  42.25            0.0           0.0
       42.75            0.0           0.0
       43.25            0.0           0.0
...                     ...           ...
 23.75 62.25            0.0           0.0
 24.25 61.25            0.0           0.0
       61.75            0.0           0.0
       62.25            0.0           0.0
 24.75 61.75            0.0           0.0

[274 rows x 10 columns]

In [9]:
importlib.reload(optimization_plots)
colors = [
    [255, 165, 0, 160],   # orange
    [50, 205, 50, 160],   # limegreen
    [0, 100, 0, 160],     # darkgreen
    [128, 0, 128, 160]    # purple
]
optimization_plots.deck_plot(optimized_data_original.reset_index().rename(columns={'Lon': 'lon', 'Lat': 'lat'}), management_forms=['spbau_manbau', 'tobd_manbau', 'tone_manbau', 'spbau_stop'], management_colors=colors)

{
  "initialViewState": {
    "latitude": 53.43978102189781,
    "longitude": 9.985401459854014,
    "zoom": 8
  },
  "layers": [
    {
      "@@type": "PolygonLayer",
      "autoHighlight": true,
      "data": [
        {
          "color": [
            255,
            165,
            0,
            160
          ],
          "name": "Portfolio",
          "polygon": [
            [
              -8.75,
              42.75
            ],
            [
              -8.688657681786628,
              42.75
            ],
            [
              -8.690091831097913,
              42.75968335316266
            ],
            [
              -8.69432721980391,
              42.768913923493706
            ],
            [
              -8.701165805836027,
              42.777260099783504
            ],
            [
              -8.71028782451194,
              42.78433162410485
            ],
            [
              -8.721266740376764,
              42.78979783983991
            ],
            [
              -8.733589191526846,
              42.79340315281618
            ],
            [
              -8.74667899384183,
              42.794978982605905
            ],
            [
              -8.759924082713734,
              42.794451645159526
            ],
            [
              -8.772705132507772,
              42.79184579818995
            ],
            [
              -8.784424515540687,
              42.787283288205266
            ],
            [
              -8.794534246487022,
              42.78097745310151
            ],
            [
              -8.802561605563882,
              42.77322314671969
            ],
            [
              -8.808131242382606,
              42.764382951807924
            ],
            [
              -8.810982726915753,
              42.75487022605513
            ],
            [
              -8.810982726915753,
              42.74512977394487
            ],
            [
              -8.808131242382606,
              42.735617048192076
            ],
            [
              -8.802561605563882,
              42.72677685328031
            ],
            [
              -8.794534246487022,
              42.71902254689849
            ],
            [
              -8.784424515540687,
              42.712716711794734
            ],
            [
              -8.772705132507772,
              42.70815420181005
            ],
            [
              -8.759924082713734,
              42.705548354840474
            ],
            [
              -8.74667899384183,
              42.705021017394095
            ],
            [
              -8.733589191526846,
              42.70659684718382
            ],
            [
              -8.721266740376764,
              42.71020216016009
            ],
            [
              -8.71028782451194,
              42.71566837589515
            ],
            [
              -8.701165805836027,
              42.722739900216496
            ],
            [
              -8.69432721980391,
              42.731086076506294
            ],
            [
              -8.690091831097913,
              42.74031664683734
            ],
            [
              -8.688657681786628,
              42.75
            ],
            [
              -8.75,
              42.75
            ]
          ],
          "slice": "spbau_manbau",
          "value": 1.0
        },
        {
          "color": [
            50,
            205,
            50,
            160
          ],
          "name": "Portfolio",
          "polygon": [
            [
              -8.75,
              42.75
            ],
            [
              -8.688657681786628,
              42.75
            ],
            [
              -8.688657681786628,
              42.75
            ],
            [
              -8.75,
              42.75
            ]
          ],
          "slice": "tobd_manbau",
          "value": 0.0
        },
        {
          "color": [
            0,
            100,
            0,
            160
          ],
          "name": "Portfolio",
          "polygon": [
            [
              -8.75,
              42.75
            ],
            [
              -8.688657681786628,
              42.75
            ],
            [
              -8.688657681786628,
              42.75
            ],
            [
              -8.75,
              42.75
            ]
          ],
          "slice": "tone_manbau",
          "value": 0.0
        },
        {
          "color": [
            128,
            0,
            128,
            160
          ],
          "name": "Portfolio",
          "polygon": [
            [
              -8.75,
              42.75
            ],
            [
              -8.688657681786628,
              42.75
            ],
            [
              -8.688657681786628,
              42.75
            ],
            [
              -8.75,
              42.75
            ]
          ],
          "slice": "spbau_stop",
          "value": 0.0
        },
        {
          "color": [
            255,
            165,
            0,
            160
          ],
          "name": "Portfolio",
          "polygon": [
            [
              -8.75,
              43.25
            ],
            [
              -8.688156451989956,
              43.25
            ],
            [
              -8.689602319775346,
              43.25968335316266
            ],
            [
              -8.693872315960842,
              43.268913923493706
            ],
            [
              -8.70076678027057,
              43.277260099783504
            ],
            [
              -8.70996333521605,
              43.28433162410485
            ],
            [
              -8.721031960109272,
              43.28979783983991
            ],
            [
              -8.73345509835212,
              43.29340315281618
            ],
            [
              -8.746651857807686,
              43.294978982605905
            ],
            [
              -8.760005172670972,
              43.294451645159526
            ],
            [
              -8.772890656780113,
              43.29184579818995
            ],
            [
              -8.784705799219354,
              43.287283288205266
            ],
            [
              -8.794898137059825,
              43.28097745310151
            ],
            [
              -8.802991087912071,
              43.27322314671969
            ],
            [
              -8.808606234388915,
              43.264382951807924
            ],
            [
              -8.811481018481883,
              43.25487022605513
            ],
            [
              -8.811481018481883,
              43.24512977394487
            ],
            [
              -8.808606234388915,
              43.235617048192076
            ],
            [
              -8.802991087912071,
              43.22677685328031
            ],
            [
              -8.794898137059825,
              43.21902254689849
            ],
            [
              -8.784705799219354,
              43.212716711794734
            ],
            [
              -8.772890656780113,
              43.20815420181005
            ],
            [
              -8.760005172670972,
              43.205548354840474
            ],
            [
              -8.746651857807686,
              43.205021017394095
            ],
            [
              -8.73345509835212,
              43.20659684718382
            ],
            [
              -8.721031960109272,
              43.21020216016009
            ],
            [
              -8.70996333521605,
              43.21566837589515
            ],
            [
              -8.70076678027057,
              43.222739900216496
            ],
            [
              -8.693872315960842,
              43.231086076506294
            ],
            [
              -8.689602319775346,
              43.24031664683734
            ],
            [
              -8.688156451989956,
              43.25
            ],
            [
              -8.75,
              43.25
            ]
          ],
          "slice": "spbau_manbau",
          "value": 1.0
        },
        {
          "color": [
            50,
            205,
            50,
            160
          ],
          "name": "Portfolio",
          "polygon": [
            [
              -8.75,
              43.25
            ],
            [
              -8.688156451989956,
              43.25
            ],
            [
              -8.688156451989956,
              43.25
            ],
            [
              -8.75,
              43.25
            ]
          ],
          "slice": "tobd_manbau",
          "value": 0.0
        },
        {
          "color": [
            0,
            100,
            0,
            160
          ],
          "name": "Portfolio",
          "polygon": [
            [
              -8.75,
              43.25
            ],
            [
              -8.688156451989956,
              43.25
            ],
            [
              -8.688156451989956,
              43.25
            ],
            [
              -8.75,
              43.25
            ]
          ],
          "slice": "tone_manbau",
          "value": 0.0
        },
        {
          "color": [
            128,
            0,
            128,
            160
          ],
          "name": "Portfolio",
          "polygon": [
            [
              -8.75,
              43.25
            ],
            [
              -8.688156451989956,
              43.25
            ],
            [
              -8.688156451989956,
              43.25
            ],
            [
              -8.75,
              43.25
            ]
          ],
          "slice": "spbau_stop",
          "value": 0.0
        },
        {
          "color": [
            255,
            165,
            0,
            160
          ],
          "name": "Portfolio",
          "polygon": [
            [
              -8.25,
              42.25
            ],
            [
              -8.189146255174835,
              42.25
            ],
            [
              -8.190568981911808,
              42.25968335316266
            ],
            [
              -8.194770637001751,
              42.268913923493706
            ],
            [
              -8.201554755722466,
              42.277260099783504
            ],
            [
              -8.210604120222575,
              42.28433162410485
            ],
            [
              -8.221495592275701,
              42.28979783983991
            ],
            [
              -8.233719898753643,
              42.29340315281618
            ],
            [
              -8.24670544467183,
              42.294978982605905
            ],
            [
              -8.259845040335527,
              42.294451645159526
            ],
            [
              -8.272524292855113,
              42.29184579818995
            ],
            [
              -8.284150334474745,
              42.287283288205266
            ],
            [
              -8.29417954440971,
              42.28097745310151
            ],
            [
              -8.302142967950115,
              42.27322314671969
            ],
            [
              -8.307668244261917,
              42.264382951807924
            ],
            [
              -8.310497017565682,
              42.25487022605513
            ],
            [
              -8.310497017565682,
              42.24512977394487
            ],
            [
              -8.307668244261917,
              42.235617048192076
            ],
            [
              -8.302142967950115,
              42.22677685328031
            ],
            [
              -8.29417954440971,
              42.21902254689849
            ],
            [
              -8.284150334474745,
              42.212716711794734
            ],
            [
              -8.272524292855113,
              42.20815420181005
            ],
            [
              -8.259845040335527,
              42.205548354840474
            ],
            [
              -8.24670544467183,
              42.205021017394095
            ],
            [
              -8.233719898753643,
              42.20659684718382
            ],
            [
              -8.221495592275701,
              42.21020216016009
            ],
            [
              -8.210604120222575,
              42.21566837589515
            ],
            [
              -8.201554755722466,
              42.222739900216496
            ],
            [
              -8.194770637001751,
              42.231086076506294
            ],
            [
              -8.190568981911808,
              42.24031664683734
            ],
            [
              -8.189146255174835,
              42.25
            ],
            [
              -8.25,
              42.25
            ]
          ],
          "slice": "spbau_manbau",
          "value": 1.0
        },
        {
          "color": [
            50,
            205,
            50,
            160
          ],
          "name": "Portfolio",
          "polygon": [
            [
              -8.25,
              42.25
            ],
            [
              -8.189146255174835,
              42.25
            ],
            [
              -8.189146255174835,
              42.25
            ],
            [
              -8.25,
              42.25
            ]
          ],
          "slice": "tobd_manbau",
          "value": 0.0
        },
        {
          "color": [
            0,
            100,
            0,
            160
          ],
          "name": "Portfolio",
          "polygon": [
            [
              -8.25,
              42.25
            ],
            [
              -8.189146255174835,
              42.25
            ],
            [
              -8.189146255174835,
              42.25
            ],
            [
              -8.25,
              42.25
            ]
          ],
          "slice": "tone_manbau",
          "value": 0.0
        },
        {
          "color": [
            128,
            0,
            128,
            160
          ],
          "name": "Portfolio",
          "polygon": [
            [
              -8.25,
              42.25
            ],
            [
              -8.189146255174835,
              42.25
            ],
            [
              -8.189146255174835,
              42.25
            ],
            [
              -8.25,
              42.25
            ]
          ],
          "slice": "spbau_stop",
          "value": 0.0
        },
        {
          "color": [
            255,
            165,
            0,
            160
          ],
          "name": "Portfolio",
          "polygon": [
            [
              -8.25,
              42.75
            ],
            [
              -8.188657681786628,
              42.75
            ],
            [
              -8.190091831097913,
              42.75968335316266
            ],
            [
              -8.19432721980391,
              42.768913923493706
            ],
            [
              -8.201165805836027,
              42.777260099783504
            ],
            [
              -8.21028782451194,
              42.78433162410485
            ],
            [
              -8.221266740376764,
              42.78979783983991
            ],
            [
              -8.233589191526846,
              42.79340315281618
            ],
            [
              -8.24667899384183,
              42.794978982605905
            ],
            [
              -8.259924082713734,
              42.794451645159526
            ],
            [
              -8.272705132507772,
              42.79184579818995
            ],
            [
              -8.284424515540687,
              42.787283288205266
            ],
            [
              -8.294534246487022,
              42.78097745310151
            ],
            [
              -8.302561605563882,
              42.77322314671969
            ],
            [
              -8.308131242382606,
              42.764382951807924
            ],
            [
              -8.310982726915753,
              42.75487022605513
            ],
            [
              -8.310982726915753,
              42.74512977394487
            ],
            [
              -8.308131242382606,
              42.735617048192076
            ],
            [
              -8.302561605563882,
              42.72677685328031
            ],
            [
              -8.294534246487022,
              42.71902254689849
            ],
            [
              -8.284424515540687,
              42.712716711794734
            ],
            [
              -8.272705132507772,
              42.70815420181005
            ],
            [
              -8.259924082713734,
              42.705548354840474
            ],
            [
              -8.24667899384183,
              42.705021017394095
            ],
            [
              -8.233589191526846,
              42.70659684718382
            ],
            [
              -8.221266740376764,
              42.71020216016009
            ],
            [
              -8.21028782451194,
              42.71566837589515
            ],
            [
              -8.201165805836027,
              42.722739900216496
            ],
            [
              -8.19432721980391,
              42.731086076506294
            ],
            [
              -8.190091831097913,
              42.74031664683734
            ],
            [
              -8.188657681786628,
              42.75
            ],
            [
              -8.25,
              42.75
            ]
          ],
          "slice": "spbau_manbau",
          "value": 1.0
        },
        {
          "color": [
            50,
            205,
            50,
            160
          ],
          "name": "Portfolio",
          "polygon": [
            [
              -8.25,
              42.75
            ],
            [
              -8.188657681786628,
              42.75
            ],
            [
              -8.188657681786628,
              42.75
            ],
            [
              -8.25,
              42.75
            ]
          ],
          "slice": "tobd_manbau",
          "value": 0.0
        },
        {
          "color": [
            0,
            100,
            0,
            160
          ],
          "name": "Portfolio",
          "polygon": [
            [
              -8.25,
              42.75
            ],
            [
              -8.188657681786628,
              42.75
            ],
            [
              -8.188657681786628,
              42.75
            ],
            [
              -8.25,
              42.75
            ]
          ],
          "slice": "tone_manbau",
          "value": 0.0
        },
        {
          "color": [
            128,
            0,
            128,
            160
          ],
          "name": "Portfolio",
          "polygon": [
            [
              -8.25,
              42.75
            ],
            [
              -8.188657681786628,
              42.75
            ],
            [
              -8.188657681786628,
              42.75
            ],
            [
              -8.25,
              42.75
            ]
          ],
          "slice": "spbau_stop",
          "value": 0.0
        },
        {
          "color": [
            255,
            165,
            0,
            160
          ],
          "name": "Portfolio",
          "polygon": [
            [
              -8.25,
              43.25
            ],
            [
              -8.188156451989956,
              43.25
            ],
            [